/*First Player*/
var fnam1,fnam2,turn=0,temp;
function startup() {
fnam1=document.getElementById("fname1").value;
fnam2=document.getElementById("fname2").value;
	if(fnam1==""||fnam2=="")
 	{
		window.alert("Enter the name of Both players.")
	} else {
		window.alert("Your game is started,Please enjoy your Game.\nClick on the dice of your side to rolling.!!")
		document.getElementById("pl1").value=fnam1;
		document.getElementById("pl2").value=fnam2;
		document.getElementById("fname1").disabled = true;
		document.getElementById("fname2").disabled = true;
	}
}
var ranNum=0,ranNum1=0,move;
var pranNum=0,pranNum1=0;
function diceNumber1() {
fnam1=document.getElementById("fname1").value;
fnam2=document.getElementById("fname2").value;
if(fnam1==""||fnam2=="")
 	{
		window.alert("First Enter the name of the players and then click on start.")
	} else {
if(turn%2==0) {
turn++;
ranNum=Math.floor(Math.random()*6+1);
if(ranNum==1) document.getElementById("pldice1").src="images/dice1.png";
else if(ranNum==2) document.getElementById("pldice1").src="images/dice2.png";
else if(ranNum==3) document.getElementById("pldice1").src="images/dice3.png";
else if(ranNum==4) document.getElementById("pldice1").src="images/dice4.png";
else if(ranNum==5) document.getElementById("pldice1").src="images/dice5.png";
else if(ranNum==6) document.getElementById("pldice1").src="images/dice6.png";
//window.alert(ranNum);
temp=ranNum1;
//window.alert(temp);
clearpre(ranNum1);
var x=101;
if(temp+ranNum==101)
{
	ranNum1=101;
} 
else if((temp+ranNum)>101)
{
	ranNum1=temp;
}
else {
ranNum1=ranNum+ranNum1;
}
//ranNum1=ranNum+ranNum1;
//window.alert(ranNum1);
//ranNum1=ranNum+ranNum1;
if(ranNum1==4) ranNum1=14;
else if(ranNum1==9) ranNum1=31;
else if(ranNum1==1) ranNum1=38;
else if(ranNum1==21) ranNum1=42;
else if(ranNum1==28) ranNum1=84;
else if(ranNum1==51) ranNum1=67;
else if(ranNum1==75) ranNum1=52;
else if(ranNum1==71) ranNum1=91;
else if(ranNum1==80) ranNum1=100;
else if(ranNum1==17) ranNum1=7;
else if(ranNum1==54) ranNum1=34;
else if(ranNum1==62) ranNum1=19;
else if(ranNum1==64) ranNum1=60;
else if(ranNum1==87) ranNum1=24;
else if(ranNum1==95) ranNum1=75;
else if(ranNum1==93) ranNum1=73;
else if(ranNum1==98) ranNum1=79;
else if(ranNum1==101)
{
	window.alert("Player"+" "+fnam1+" "+"wins!");
	window.location.href="index.html?submit=Start";

}
moveChipRed(ranNum1);
}
else {
window.alert("It is not your turn!");
}
}
}
function moveChipRed(a) {
	if(a==1) document.getElementById('f1').style.backgroundColor="pink";
	else if(a==2) document.getElementById('f2').style.backgroundColor="pink";
	else if(a==3) document.getElementById('f3').style.backgroundColor="pink";
	else if(a==4) document.getElementById('f4').style.backgroundColor="pink";
	else if(a==5) document.getElementById('f5').style.backgroundColor="pink";
	else if(a==6) document.getElementById('f6').style.backgroundColor="pink";
	else if(a==7) document.getElementById('f7').style.backgroundColor="pink";
	else if(a==8) document.getElementById('f8').style.backgroundColor="pink";
	else if(a==9) document.getElementById('f9').style.backgroundColor="pink";
	else if(a==10) document.getElementById('f10').style.backgroundColor="pink";
	else if(a==11) document.getElementById('f11').style.backgroundColor="pink";
	else if(a==12) document.getElementById('f12').style.backgroundColor="pink";
	else if(a==13) document.getElementById('f13').style.backgroundColor="pink";
	else if(a==14) document.getElementById('f14').style.backgroundColor="pink";
	else if(a==15) document.getElementById('f15').style.backgroundColor="pink";
	else if(a==16) document.getElementById('f16').style.backgroundColor="pink";
	else if(a==17) document.getElementById('f17').style.backgroundColor="pink";
	else if(a==18) document.getElementById('f18').style.backgroundColor="pink";
	else if(a==19) document.getElementById('f19').style.backgroundColor="pink";
	else if(a==20) document.getElementById('f20').style.backgroundColor="pink";
	else if(a==21) document.getElementById('f21').style.backgroundColor="pink";
	else if(a==22) document.getElementById('f22').style.backgroundColor="pink";
	else if(a==23) document.getElementById('f23').style.backgroundColor="pink";
	else if(a==24) document.getElementById('f24').style.backgroundColor="pink";
	else if(a==25) document.getElementById('f25').style.backgroundColor="pink";
	else if(a==26) document.getElementById('f26').style.backgroundColor="pink";
	else if(a==27) document.getElementById('f27').style.backgroundColor="pink";
	else if(a==28) document.getElementById('f28').style.backgroundColor="pink";
	else if(a==29) document.getElementById('f29').style.backgroundColor="pink";
	else if(a==30) document.getElementById('f30').style.backgroundColor="pink";
	else if(a==31) document.getElementById('f31').style.backgroundColor="pink";
	else if(a==32) document.getElementById('f32').style.backgroundColor="pink";
	else if(a==33) document.getElementById('f33').style.backgroundColor="pink";
	else if(a==34) document.getElementById('f34').style.backgroundColor="pink";
	else if(a==35) document.getElementById('f35').style.backgroundColor="pink";
	else if(a==36) document.getElementById('f36').style.backgroundColor="pink";
	else if(a==37) document.getElementById('f37').style.backgroundColor="pink";
	else if(a==38) document.getElementById('f38').style.backgroundColor="pink";
	else if(a==39) document.getElementById('f39').style.backgroundColor="pink";
	else if(a==40) document.getElementById('f40').style.backgroundColor="pink";
	else if(a==41) document.getElementById('f41').style.backgroundColor="pink";
	else if(a==42) document.getElementById('f42').style.backgroundColor="pink";
	else if(a==43) document.getElementById('f43').style.backgroundColor="pink";
	else if(a==44) document.getElementById('f44').style.backgroundColor="pink";
	else if(a==45) document.getElementById('f45').style.backgroundColor="pink";
	else if(a==46) document.getElementById('f46').style.backgroundColor="pink";
	else if(a==47) document.getElementById('f47').style.backgroundColor="pink";
	else if(a==48) document.getElementById('f48').style.backgroundColor="pink";
	else if(a==49) document.getElementById('f49').style.backgroundColor="pink";
	else if(a==50) document.getElementById('f50').style.backgroundColor="pink";
	else if(a==51) document.getElementById('f51').style.backgroundColor="pink";
	else if(a==52) document.getElementById('f52').style.backgroundColor="pink";
	else if(a==53) document.getElementById('f53').style.backgroundColor="pink";
	else if(a==54) document.getElementById('f54').style.backgroundColor="pink";
	else if(a==55) document.getElementById('f55').style.backgroundColor="pink";
	else if(a==56) document.getElementById('f56').style.backgroundColor="pink";
	else if(a==57) document.getElementById('f57').style.backgroundColor="pink";
	else if(a==58) document.getElementById('f58').style.backgroundColor="pink";
	else if(a==59) document.getElementById('f59').style.backgroundColor="pink";
	else if(a==60) document.getElementById('f60').style.backgroundColor="pink";
	else if(a==61) document.getElementById('f61').style.backgroundColor="pink";
	else if(a==62) document.getElementById('f62').style.backgroundColor="pink";
	else if(a==63) document.getElementById('f63').style.backgroundColor="pink";
	else if(a==64) document.getElementById('f64').style.backgroundColor="pink";
	else if(a==65) document.getElementById('f65').style.backgroundColor="pink";
	else if(a==66) document.getElementById('f66').style.backgroundColor="pink";
	else if(a==67) document.getElementById('f67').style.backgroundColor="pink";
	else if(a==68) document.getElementById('f68').style.backgroundColor="pink";
	else if(a==69) document.getElementById('f69').style.backgroundColor="pink";
	else if(a==70) document.getElementById('f70').style.backgroundColor="pink";
	else if(a==71) document.getElementById('f71').style.backgroundColor="pink";
	else if(a==72) document.getElementById('f72').style.backgroundColor="pink";
	else if(a==73) document.getElementById('f73').style.backgroundColor="pink";
	else if(a==74) document.getElementById('f74').style.backgroundColor="pink";
	else if(a==75) document.getElementById('f75').style.backgroundColor="pink";
	else if(a==76) document.getElementById('f76').style.backgroundColor="pink";
	else if(a==77) document.getElementById('f77').style.backgroundColor="pink";
	else if(a==78) document.getElementById('f78').style.backgroundColor="pink";
	else if(a==79) document.getElementById('f79').style.backgroundColor="pink";
	else if(a==80) document.getElementById('f80').style.backgroundColor="pink";
	else if(a==81) document.getElementById('f81').style.backgroundColor="pink";
	else if(a==82) document.getElementById('f82').style.backgroundColor="pink";
	else if(a==83) document.getElementById('f83').style.backgroundColor="pink";
	else if(a==84) document.getElementById('f84').style.backgroundColor="pink";
	else if(a==85) document.getElementById('f85').style.backgroundColor="pink";
	else if(a==86) document.getElementById('f86').style.backgroundColor="pink";
	else if(a==87) document.getElementById('f87').style.backgroundColor="pink";
	else if(a==88) document.getElementById('f88').style.backgroundColor="pink";
	else if(a==89) document.getElementById('f89').style.backgroundColor="pink";
	else if(a==90) document.getElementById('f90').style.backgroundColor="pink";
	else if(a==91) document.getElementById('f91').style.backgroundColor="pink";
	else if(a==92) document.getElementById('f92').style.backgroundColor="pink";
	else if(a==93) document.getElementById('f93').style.backgroundColor="pink";
	else if(a==94) document.getElementById('f94').style.backgroundColor="pink";
	else if(a==95) document.getElementById('f95').style.backgroundColor="pink";
	else if(a==96) document.getElementById('f96').style.backgroundColor="pink";
	else if(a==97) document.getElementById('f97').style.backgroundColor="pink";
	else if(a==98) document.getElementById('f98').style.backgroundColor="pink";
	else if(a==99) document.getElementById('f99').style.backgroundColor="pink";
	else if(a==100) document.getElementById('f100').style.backgroundColor="pink";
	else if(a>100) 
	{
		var z=101-temp;
		if(temp==1) document.getElementById('f1').style.backgroundColor="pink";
	else if(temp==2) document.getElementById('f2').style.backgroundColor="pink";
	else if(temp==3) document.getElementById('f3').style.backgroundColor="pink";
	else if(temp==4) document.getElementById('f4').style.backgroundColor="pink";
	else if(temp==5) document.getElementById('f5').style.backgroundColor="pink";
	else if(temp==6) document.getElementById('f6').style.backgroundColor="pink";
	else if(temp==7) document.getElementById('f7').style.backgroundColor="pink";
	else if(temp==8) document.getElementById('f8').style.backgroundColor="pink";
	else if(temp==9) document.getElementById('f9').style.backgroundColor="pink";
	else if(temp==10) document.getElementById('f10').style.backgroundColor="pink";
	else if(temp==11) document.getElementById('f11').style.backgroundColor="pink";
	else if(temp==12) document.getElementById('f12').style.backgroundColor="pink";
	else if(temp==13) document.getElementById('f13').style.backgroundColor="pink";
	else if(temp==14) document.getElementById('f14').style.backgroundColor="pink";
	else if(temp==15) document.getElementById('f15').style.backgroundColor="pink";
	else if(temp==16) document.getElementById('f16').style.backgroundColor="pink";
	else if(temp==17) document.getElementById('f17').style.backgroundColor="pink";
	else if(temp==18) document.getElementById('f18').style.backgroundColor="pink";
	else if(temp==19) document.getElementById('f19').style.backgroundColor="pink";
	else if(temp==20) document.getElementById('f20').style.backgroundColor="pink";
	else if(temp==21) document.getElementById('f21').style.backgroundColor="pink";
	else if(temp==22) document.getElementById('f22').style.backgroundColor="pink";
	else if(temp==23) document.getElementById('f23').style.backgroundColor="pink";
	else if(temp==24) document.getElementById('f24').style.backgroundColor="pink";
	else if(temp==25) document.getElementById('f25').style.backgroundColor="pink";
	else if(temp==26) document.getElementById('f26').style.backgroundColor="pink";
	else if(temp==27) document.getElementById('f27').style.backgroundColor="pink";
	else if(temp==28) document.getElementById('f28').style.backgroundColor="pink";
	else if(temp==29) document.getElementById('f29').style.backgroundColor="pink";
	else if(temp==30) document.getElementById('f30').style.backgroundColor="pink";
	else if(temp==31) document.getElementById('f31').style.backgroundColor="pink";
	else if(temp==32) document.getElementById('f32').style.backgroundColor="pink";
	else if(temp==33) document.getElementById('f33').style.backgroundColor="pink";
	else if(temp==34) document.getElementById('f34').style.backgroundColor="pink";
	else if(temp==35) document.getElementById('f35').style.backgroundColor="pink";
	else if(temp==36) document.getElementById('f36').style.backgroundColor="pink";
	else if(temp==37) document.getElementById('f37').style.backgroundColor="pink";
	else if(temp==38) document.getElementById('f38').style.backgroundColor="pink";
	else if(temp==39) document.getElementById('f39').style.backgroundColor="pink";
	else if(temp==40) document.getElementById('f40').style.backgroundColor="pink";
	else if(temp==41) document.getElementById('f41').style.backgroundColor="pink";
	else if(temp==42) document.getElementById('f42').style.backgroundColor="pink";
	else if(temp==43) document.getElementById('f43').style.backgroundColor="pink";
	else if(temp==44) document.getElementById('f44').style.backgroundColor="pink";
	else if(temp==45) document.getElementById('f45').style.backgroundColor="pink";
	else if(temp==46) document.getElementById('f46').style.backgroundColor="pink";
	else if(temp==47) document.getElementById('f47').style.backgroundColor="pink";
	else if(temp==48) document.getElementById('f48').style.backgroundColor="pink";
	else if(temp==49) document.getElementById('f49').style.backgroundColor="pink";
	else if(temp==50) document.getElementById('f50').style.backgroundColor="pink";
	else if(temp==51) document.getElementById('f51').style.backgroundColor="pink";
	else if(temp==52) document.getElementById('f52').style.backgroundColor="pink";
	else if(temp==53) document.getElementById('f53').style.backgroundColor="pink";
	else if(temp==54) document.getElementById('f54').style.backgroundColor="pink";
	else if(temp==55) document.getElementById('f55').style.backgroundColor="pink";
	else if(temp==56) document.getElementById('f56').style.backgroundColor="pink";
	else if(temp==57) document.getElementById('f57').style.backgroundColor="pink";
	else if(temp==58) document.getElementById('f58').style.backgroundColor="pink";
	else if(temp==59) document.getElementById('f59').style.backgroundColor="pink";
	else if(temp==60) document.getElementById('f60').style.backgroundColor="pink";
	else if(temp==61) document.getElementById('f61').style.backgroundColor="pink";
	else if(temp==62) document.getElementById('f62').style.backgroundColor="pink";
	else if(temp==63) document.getElementById('f63').style.backgroundColor="pink";
	else if(temp==64) document.getElementById('f64').style.backgroundColor="pink";
	else if(temp==65) document.getElementById('f65').style.backgroundColor="pink";
	else if(temp==66) document.getElementById('f66').style.backgroundColor="pink";
	else if(temp==67) document.getElementById('f67').style.backgroundColor="pink";
	else if(temp==68) document.getElementById('f68').style.backgroundColor="pink";
	else if(temp==69) document.getElementById('f69').style.backgroundColor="pink";
	else if(temp==70) document.getElementById('f70').style.backgroundColor="pink";
	else if(temp==71) document.getElementById('f71').style.backgroundColor="pink";
	else if(temp==72) document.getElementById('f72').style.backgroundColor="pink";
	else if(temp==73) document.getElementById('f73').style.backgroundColor="pink";
	else if(temp==74) document.getElementById('f74').style.backgroundColor="pink";
	else if(temp==75) document.getElementById('f75').style.backgroundColor="pink";
	else if(temp==76) document.getElementById('f76').style.backgroundColor="pink";
	else if(temp==77) document.getElementById('f77').style.backgroundColor="pink";
	else if(temp==78) document.getElementById('f78').style.backgroundColor="pink";
	else if(temp==79) document.getElementById('f79').style.backgroundColor="pink";
	else if(temp==80) document.getElementById('f80').style.backgroundColor="pink";
	else if(temp==81) document.getElementById('f81').style.backgroundColor="pink";
	else if(temp==82) document.getElementById('f82').style.backgroundColor="pink";
	else if(temp==83) document.getElementById('f83').style.backgroundColor="pink";
	else if(temp==84) document.getElementById('f84').style.backgroundColor="pink";
	else if(temp==85) document.getElementById('f85').style.backgroundColor="pink";
	else if(temp==86) document.getElementById('f86').style.backgroundColor="pink";
	else if(temp==87) document.getElementById('f87').style.backgroundColor="pink";
	else if(temp==88) document.getElementById('f88').style.backgroundColor="pink";
	else if(temp==89) document.getElementById('f89').style.backgroundColor="pink";
	else if(temp==90) document.getElementById('f90').style.backgroundColor="pink";
	else if(temp==91) document.getElementById('f91').style.backgroundColor="pink";
	else if(temp==92) document.getElementById('f92').style.backgroundColor="pink";
	else if(temp==93) document.getElementById('f93').style.backgroundColor="pink";
	else if(temp==94) document.getElementById('f94').style.backgroundColor="pink";
	else if(temp==95) document.getElementById('f95').style.backgroundColor="pink";
	else if(temp==96) document.getElementById('f96').style.backgroundColor="pink";
	else if(temp==97) document.getElementById('f97').style.backgroundColor="pink";
	else if(temp==98) document.getElementById('f98').style.backgroundColor="pink";
	else if(temp==99) document.getElementById('f99').style.backgroundColor="pink";
	else if(temp==100) document.getElementById('f100').style.backgroundColor="pink";
		window.alert("You need"+" "+z+" "+"to win");
	}
	return a;	
}
function clearpre(b) {
if(b==1)document.getElementById("f1").style.backgroundColor="transparent";
else if(b==2)document.getElementById("f2").style.backgroundColor="transparent";
else if(b==3)document.getElementById("f3").style.backgroundColor="transparent";
else if(b==4)document.getElementById("f4").style.backgroundColor="transparent";
else if(b==5)document.getElementById("f5").style.backgroundColor="transparent";
else if(b==6)document.getElementById("f6").style.backgroundColor="transparent";
else if(b==7)document.getElementById("f7").style.backgroundColor="transparent";
else if(b==8)document.getElementById("f8").style.backgroundColor="transparent";
else if(b==9)document.getElementById("f9").style.backgroundColor="transparent";
else if(b==10)document.getElementById("f10").style.backgroundColor="transparent";
else if(b==11)document.getElementById("f11").style.backgroundColor="transparent";
else if(b==12)document.getElementById("f12").style.backgroundColor="transparent";
else if(b==13)document.getElementById("f13").style.backgroundColor="transparent";
else if(b==14)document.getElementById("f14").style.backgroundColor="transparent";
else if(b==15)document.getElementById("f15").style.backgroundColor="transparent";
else if(b==16)document.getElementById("f16").style.backgroundColor="transparent";
else if(b==17)document.getElementById("f17").style.backgroundColor="transparent";
else if(b==18)document.getElementById("f18").style.backgroundColor="transparent";
else if(b==19)document.getElementById("f19").style.backgroundColor="transparent";
else if(b==20)document.getElementById("f20").style.backgroundColor="transparent";
else if(b==21)document.getElementById("f21").style.backgroundColor="transparent";
else if(b==22)document.getElementById("f22").style.backgroundColor="transparent";
else if(b==23)document.getElementById("f23").style.backgroundColor="transparent";
else if(b==24)document.getElementById("f24").style.backgroundColor="transparent";
else if(b==25)document.getElementById("f25").style.backgroundColor="transparent";
else if(b==26)document.getElementById("f26").style.backgroundColor="transparent";
else if(b==27)document.getElementById("f27").style.backgroundColor="transparent";
else if(b==28)document.getElementById("f28").style.backgroundColor="transparent";
else if(b==29)document.getElementById("f29").style.backgroundColor="transparent";
else if(b==30)document.getElementById("f30").style.backgroundColor="transparent";
else if(b==31)document.getElementById("f31").style.backgroundColor="transparent";
else if(b==32)document.getElementById("f32").style.backgroundColor="transparent";
else if(b==33)document.getElementById("f33").style.backgroundColor="transparent";
else if(b==34)document.getElementById("f34").style.backgroundColor="transparent";
else if(b==35)document.getElementById("f35").style.backgroundColor="transparent";
else if(b==36)document.getElementById("f36").style.backgroundColor="transparent";
else if(b==37)document.getElementById("f37").style.backgroundColor="transparent";
else if(b==38)document.getElementById("f38").style.backgroundColor="transparent";
else if(b==39)document.getElementById("f39").style.backgroundColor="transparent";
else if(b==40)document.getElementById("f40").style.backgroundColor="transparent";
else if(b==41)document.getElementById("f41").style.backgroundColor="transparent";
else if(b==42)document.getElementById("f42").style.backgroundColor="transparent";
else if(b==43)document.getElementById("f43").style.backgroundColor="transparent";
else if(b==44)document.getElementById("f44").style.backgroundColor="transparent";
else if(b==45)document.getElementById("f45").style.backgroundColor="transparent";	
else if(b==46)document.getElementById("f46").style.backgroundColor="transparent";
else if(b==47)document.getElementById("f47").style.backgroundColor="transparent";
else if(b==48)document.getElementById("f48").style.backgroundColor="transparent";
else if(b==49)document.getElementById("f49").style.backgroundColor="transparent";
else if(b==50)document.getElementById("f50").style.backgroundColor="transparent";
else if(b==51)document.getElementById("f51").style.backgroundColor="transparent";
else if(b==52)document.getElementById("f52").style.backgroundColor="transparent";
else if(b==53)document.getElementById("f53").style.backgroundColor="transparent";
else if(b==54)document.getElementById("f54").style.backgroundColor="transparent";
else if(b==55)document.getElementById("f55").style.backgroundColor="transparent";
else if(b==56)document.getElementById("f56").style.backgroundColor="transparent";
else if(b==57)document.getElementById("f57").style.backgroundColor="transparent";
else if(b==58)document.getElementById("f58").style.backgroundColor="transparent";
else if(b==59)document.getElementById("f59").style.backgroundColor="transparent";
else if(b==60)document.getElementById("f60").style.backgroundColor="transparent";
else if(b==61)document.getElementById("f61").style.backgroundColor="transparent";
else if(b==62)document.getElementById("f62").style.backgroundColor="transparent";
else if(b==63)document.getElementById("f63").style.backgroundColor="transparent";
else if(b==64)document.getElementById("f64").style.backgroundColor="transparent";
else if(b==65)document.getElementById("f65").style.backgroundColor="transparent";
else if(b==66)document.getElementById("f66").style.backgroundColor="transparent";
else if(b==67)document.getElementById("f67").style.backgroundColor="transparent";
else if(b==68)document.getElementById("f68").style.backgroundColor="transparent";
else if(b==69)document.getElementById("f69").style.backgroundColor="transparent";
else if(b==70)document.getElementById("f70").style.backgroundColor="transparent";
else if(b==71)document.getElementById("f71").style.backgroundColor="transparent";
else if(b==72)document.getElementById("f72").style.backgroundColor="transparent";
else if(b==73)document.getElementById("f73").style.backgroundColor="transparent";
else if(b==74)document.getElementById("f74").style.backgroundColor="transparent";
else if(b==75)document.getElementById("f75").style.backgroundColor="transparent";
else if(b==76)document.getElementById("f76").style.backgroundColor="transparent";
else if(b==77)document.getElementById("f77").style.backgroundColor="transparent";
else if(b==78)document.getElementById("f78").style.backgroundColor="transparent";
else if(b==79)document.getElementById("f79").style.backgroundColor="transparent";
else if(b==80)document.getElementById("f80").style.backgroundColor="transparent";
else if(b==81)document.getElementById("f81").style.backgroundColor="transparent";
else if(b==82)document.getElementById("f82").style.backgroundColor="transparent";
else if(b==83)document.getElementById("f83").style.backgroundColor="transparent";
else if(b==84)document.getElementById("f84").style.backgroundColor="transparent";
else if(b==85)document.getElementById("f85").style.backgroundColor="transparent";
else if(b==86)document.getElementById("f86").style.backgroundColor="transparent";
else if(b==87)document.getElementById("f87").style.backgroundColor="transparent";
else if(b==88)document.getElementById("f88").style.backgroundColor="transparent";
else if(b==89)document.getElementById("f89").style.backgroundColor="transparent";
else if(b==90)document.getElementById("f90").style.backgroundColor="transparent";
else if(b==91)document.getElementById("f91").style.backgroundColor="transparent";
else if(b==92)document.getElementById("f92").style.backgroundColor="transparent";
else if(b==93)document.getElementById("f93").style.backgroundColor="transparent";
else if(b==94)document.getElementById("f94").style.backgroundColor="transparent";
else if(b==95)document.getElementById("f95").style.backgroundColor="transparent";
else if(b==96)document.getElementById("f96").style.backgroundColor="transparent";
else if(b==97)document.getElementById("f97").style.backgroundColor="transparent";
else if(b==98)document.getElementById("f98").style.backgroundColor="transparent";
else if(b==99)document.getElementById("f99").style.backgroundColor="transparent";
else if(b==100)document.getElementById("f100").style.backgroundColor="black";
}
/*Second Player*/
function diceNumber2() {
fnam1=document.getElementById("fname1").value;
fnam2=document.getElementById("fname2").value;
if(fnam1==""||fnam2=="")
 	{
		window.alert("First Enter the name of the players and then click on start.")
	} else {
if(turn%2!=0)
{
turn++;
pranNum=Math.floor(Math.random()*6+1);
if(pranNum==1) document.getElementById("pldice2").src="images/dice1.png";
else if(pranNum==2) document.getElementById("pldice2").src="images/dice2.png";
else if(pranNum==3) document.getElementById("pldice2").src="images/dice3.png";
else if(pranNum==4) document.getElementById("pldice2").src="images/dice4.png";
else if(pranNum==5) document.getElementById("pldice2").src="images/dice5.png";
else if(pranNum==6) document.getElementById("pldice2").src="images/dice6.png";
//window.alert(pranNum);
var temp1=pranNum1;
clearprep(pranNum1);
var y=101;
if(temp1+pranNum==101)
{
	pranNum1=101;
} 
else if((temp1+pranNum)>101)
{
	pranNum1=temp1;
}
else {
pranNum1=pranNum+pranNum1;
}
//pranNum1=pranNum+pranNum1;
if(pranNum1==4) pranNum1=14;
else if(pranNum1==9) pranNum1=31;
else if(pranNum1==1) pranNum1=38;
else if(pranNum1==21) pranNum1=42;
else if(pranNum1==28) pranNum1=84;
else if(pranNum1==51) pranNum1=67;
else if(pranNum1==75) pranNum1=52;
else if(pranNum1==71) pranNum1=91;
else if(pranNum1==80) pranNum1=100;
else if(pranNum1==17) pranNum1=7;
else if(pranNum1==54) pranNum1=34;
else if(pranNum1==62) pranNum1=19;
else if(pranNum1==64) pranNum1=60;
else if(pranNum1==87) pranNum1=24;
else if(pranNum1==95) pranNum1=75;
else if(pranNum1==93) pranNum1=73;
else if(pranNum1==98) pranNum1=79;
else if(pranNum1==101)
{
	window.alert("Player"+" "+fnam2+" "+"wins!");
	window.location.href="index.html?submit=Start";
}
moveChipGreen(pranNum1);
} else {
window.alert("It is not your turn!");
}
}
}
function moveChipGreen(a) {
if(a==1) document.getElementById('f1').style.backgroundColor="#21ff1c";
	else if(a==2) document.getElementById('f2').style.backgroundColor="#21ff1c";
	else if(a==3) document.getElementById('f3').style.backgroundColor="#21ff1c";
	else if(a==4) document.getElementById('f4').style.backgroundColor="#21ff1c";
	else if(a==5) document.getElementById('f5').style.backgroundColor="#21ff1c";
	else if(a==6) document.getElementById('f6').style.backgroundColor="#21ff1c";
	else if(a==7) document.getElementById('f7').style.backgroundColor="#21ff1c";
	else if(a==8) document.getElementById('f8').style.backgroundColor="#21ff1c";
	else if(a==9) document.getElementById('f9').style.backgroundColor="#21ff1c";
	else if(a==10) document.getElementById('f10').style.backgroundColor="#21ff1c";
	else if(a==11) document.getElementById('f11').style.backgroundColor="#21ff1c";
	else if(a==12) document.getElementById('f12').style.backgroundColor="#21ff1c";
	else if(a==13) document.getElementById('f13').style.backgroundColor="#21ff1c";
	else if(a==14) document.getElementById('f14').style.backgroundColor="#21ff1c";
	else if(a==15) document.getElementById('f15').style.backgroundColor="#21ff1c";
	else if(a==16) document.getElementById('f16').style.backgroundColor="#21ff1c";
	else if(a==17) document.getElementById('f17').style.backgroundColor="#21ff1c";
	else if(a==18) document.getElementById('f18').style.backgroundColor="#21ff1c";
	else if(a==19) document.getElementById('f19').style.backgroundColor="#21ff1c";
	else if(a==20) document.getElementById('f20').style.backgroundColor="#21ff1c";
	else if(a==21) document.getElementById('f21').style.backgroundColor="#21ff1c";
	else if(a==22) document.getElementById('f22').style.backgroundColor="#21ff1c";
	else if(a==23) document.getElementById('f23').style.backgroundColor="#21ff1c";
	else if(a==24) document.getElementById('f24').style.backgroundColor="#21ff1c";
	else if(a==25) document.getElementById('f25').style.backgroundColor="#21ff1c";
	else if(a==26) document.getElementById('f26').style.backgroundColor="#21ff1c";
	else if(a==27) document.getElementById('f27').style.backgroundColor="#21ff1c";
	else if(a==28) document.getElementById('f28').style.backgroundColor="#21ff1c";
	else if(a==29) document.getElementById('f29').style.backgroundColor="#21ff1c";
	else if(a==30) document.getElementById('f30').style.backgroundColor="#21ff1c";
	else if(a==31) document.getElementById('f31').style.backgroundColor="#21ff1c";
	else if(a==32) document.getElementById('f32').style.backgroundColor="#21ff1c";
	else if(a==33) document.getElementById('f33').style.backgroundColor="#21ff1c";
	else if(a==34) document.getElementById('f34').style.backgroundColor="#21ff1c";
	else if(a==35) document.getElementById('f35').style.backgroundColor="#21ff1c";
	else if(a==36) document.getElementById('f36').style.backgroundColor="#21ff1c";
	else if(a==37) document.getElementById('f37').style.backgroundColor="#21ff1c";
	else if(a==38) document.getElementById('f38').style.backgroundColor="#21ff1c";
	else if(a==39) document.getElementById('f39').style.backgroundColor="#21ff1c";
	else if(a==40) document.getElementById('f40').style.backgroundColor="#21ff1c";
	else if(a==41) document.getElementById('f41').style.backgroundColor="#21ff1c";
	else if(a==42) document.getElementById('f42').style.backgroundColor="#21ff1c";
	else if(a==43) document.getElementById('f43').style.backgroundColor="#21ff1c";
	else if(a==44) document.getElementById('f44').style.backgroundColor="#21ff1c";
	else if(a==45) document.getElementById('f45').style.backgroundColor="#21ff1c";
	else if(a==46) document.getElementById('f46').style.backgroundColor="#21ff1c";
	else if(a==47) document.getElementById('f47').style.backgroundColor="#21ff1c";
	else if(a==48) document.getElementById('f48').style.backgroundColor="#21ff1c";
	else if(a==49) document.getElementById('f49').style.backgroundColor="#21ff1c";
	else if(a==50) document.getElementById('f50').style.backgroundColor="#21ff1c";
	else if(a==51) document.getElementById('f51').style.backgroundColor="#21ff1c";
	else if(a==52) document.getElementById('f52').style.backgroundColor="#21ff1c";
	else if(a==53) document.getElementById('f53').style.backgroundColor="#21ff1c";
	else if(a==54) document.getElementById('f54').style.backgroundColor="#21ff1c";
	else if(a==55) document.getElementById('f55').style.backgroundColor="#21ff1c";
	else if(a==56) document.getElementById('f56').style.backgroundColor="#21ff1c";
	else if(a==57) document.getElementById('f57').style.backgroundColor="#21ff1c";
	else if(a==58) document.getElementById('f58').style.backgroundColor="#21ff1c";
	else if(a==59) document.getElementById('f59').style.backgroundColor="#21ff1c";
	else if(a==60) document.getElementById('f60').style.backgroundColor="#21ff1c";
	else if(a==61) document.getElementById('f61').style.backgroundColor="#21ff1c";
	else if(a==62) document.getElementById('f62').style.backgroundColor="#21ff1c";
	else if(a==63) document.getElementById('f63').style.backgroundColor="#21ff1c";
	else if(a==64) document.getElementById('f64').style.backgroundColor="#21ff1c";
	else if(a==65) document.getElementById('f65').style.backgroundColor="#21ff1c";
	else if(a==66) document.getElementById('f66').style.backgroundColor="#21ff1c";
	else if(a==67) document.getElementById('f67').style.backgroundColor="#21ff1c";
	else if(a==68) document.getElementById('f68').style.backgroundColor="#21ff1c";
	else if(a==69) document.getElementById('f69').style.backgroundColor="#21ff1c";
	else if(a==70) document.getElementById('f70').style.backgroundColor="#21ff1c";
	else if(a==71) document.getElementById('f71').style.backgroundColor="#21ff1c";
	else if(a==72) document.getElementById('f72').style.backgroundColor="#21ff1c";
	else if(a==73) document.getElementById('f73').style.backgroundColor="#21ff1c";
	else if(a==74) document.getElementById('f74').style.backgroundColor="#21ff1c";
	else if(a==75) document.getElementById('f75').style.backgroundColor="#21ff1c";
	else if(a==76) document.getElementById('f76').style.backgroundColor="#21ff1c";
	else if(a==77) document.getElementById('f77').style.backgroundColor="#21ff1c";
	else if(a==78) document.getElementById('f78').style.backgroundColor="#21ff1c";
	else if(a==79) document.getElementById('f79').style.backgroundColor="#21ff1c";
	else if(a==80) document.getElementById('f80').style.backgroundColor="#21ff1c";
	else if(a==81) document.getElementById('f81').style.backgroundColor="#21ff1c";
	else if(a==82) document.getElementById('f82').style.backgroundColor="#21ff1c";
	else if(a==83) document.getElementById('f83').style.backgroundColor="#21ff1c";
	else if(a==84) document.getElementById('f84').style.backgroundColor="#21ff1c";
	else if(a==85) document.getElementById('f85').style.backgroundColor="#21ff1c";
	else if(a==86) document.getElementById('f86').style.backgroundColor="#21ff1c";
	else if(a==87) document.getElementById('f87').style.backgroundColor="#21ff1c";
	else if(a==88) document.getElementById('f88').style.backgroundColor="#21ff1c";
	else if(a==89) document.getElementById('f89').style.backgroundColor="#21ff1c";
	else if(a==90) document.getElementById('f90').style.backgroundColor="#21ff1c";
	else if(a==91) document.getElementById('f91').style.backgroundColor="#21ff1c";
	else if(a==92) document.getElementById('f92').style.backgroundColor="#21ff1c";
	else if(a==93) document.getElementById('f93').style.backgroundColor="#21ff1c";
	else if(a==94) document.getElementById('f94').style.backgroundColor="#21ff1c";
	else if(a==95) document.getElementById('f95').style.backgroundColor="#21ff1c";
	else if(a==96) document.getElementById('f96').style.backgroundColor="#21ff1c";
	else if(a==97) document.getElementById('f97').style.backgroundColor="#21ff1c";
	else if(a==98) document.getElementById('f98').style.backgroundColor="#21ff1c";
	else if(a==99) document.getElementById('f99').style.backgroundColor="#21ff1c";
	else if(a==100) document.getElementById('f100').style.backgroundColor="#21ff1c";
	else if(a>100) 
	{
		var z=101-temp1;
		if(temp1==1) document.getElementById('f1').style.backgroundColor="#21ff1c";
	else if(temp1==2) document.getElementById('f2').style.backgroundColor="#21ff1c";
	else if(temp1==3) document.getElementById('f3').style.backgroundColor="#21ff1c";
	else if(temp1==4) document.getElementById('f4').style.backgroundColor="#21ff1c";
	else if(temp1==5) document.getElementById('f5').style.backgroundColor="#21ff1c";
	else if(temp1==6) document.getElementById('f6').style.backgroundColor="#21ff1c";
	else if(temp1==7) document.getElementById('f7').style.backgroundColor="#21ff1c";
	else if(temp1==8) document.getElementById('f8').style.backgroundColor="#21ff1c";
	else if(temp1==9) document.getElementById('f9').style.backgroundColor="#21ff1c";
	else if(temp1==10) document.getElementById('f10').style.backgroundColor="#21ff1c";
	else if(temp1==11) document.getElementById('f11').style.backgroundColor="#21ff1c";
	else if(temp1==12) document.getElementById('f12').style.backgroundColor="#21ff1c";
	else if(temp1==13) document.getElementById('f13').style.backgroundColor="#21ff1c";
	else if(temp1==14) document.getElementById('f14').style.backgroundColor="#21ff1c";
	else if(temp1==15) document.getElementById('f15').style.backgroundColor="#21ff1c";
	else if(temp1==16) document.getElementById('f16').style.backgroundColor="#21ff1c";
	else if(temp1==17) document.getElementById('f17').style.backgroundColor="#21ff1c";
	else if(temp1==18) document.getElementById('f18').style.backgroundColor="#21ff1c";
	else if(temp1==19) document.getElementById('f19').style.backgroundColor="#21ff1c";
	else if(temp1==20) document.getElementById('f20').style.backgroundColor="#21ff1c";
	else if(temp1==21) document.getElementById('f21').style.backgroundColor="#21ff1c";
	else if(temp1==22) document.getElementById('f22').style.backgroundColor="#21ff1c";
	else if(temp1==23) document.getElementById('f23').style.backgroundColor="#21ff1c";
	else if(temp1==24) document.getElementById('f24').style.backgroundColor="#21ff1c";
	else if(temp1==25) document.getElementById('f25').style.backgroundColor="#21ff1c";
	else if(temp1==26) document.getElementById('f26').style.backgroundColor="#21ff1c";
	else if(temp1==27) document.getElementById('f27').style.backgroundColor="#21ff1c";
	else if(temp1==28) document.getElementById('f28').style.backgroundColor="#21ff1c";
	else if(temp1==29) document.getElementById('f29').style.backgroundColor="#21ff1c";
	else if(temp1==30) document.getElementById('f30').style.backgroundColor="#21ff1c";
	else if(temp1==31) document.getElementById('f31').style.backgroundColor="#21ff1c";
	else if(temp1==32) document.getElementById('f32').style.backgroundColor="#21ff1c";
	else if(temp1==33) document.getElementById('f33').style.backgroundColor="#21ff1c";
	else if(temp1==34) document.getElementById('f34').style.backgroundColor="#21ff1c";
	else if(temp1==35) document.getElementById('f35').style.backgroundColor="#21ff1c";
	else if(temp1==36) document.getElementById('f36').style.backgroundColor="#21ff1c";
	else if(temp1==37) document.getElementById('f37').style.backgroundColor="#21ff1c";
	else if(temp1==38) document.getElementById('f38').style.backgroundColor="#21ff1c";
	else if(temp1==39) document.getElementById('f39').style.backgroundColor="#21ff1c";
	else if(temp1==40) document.getElementById('f40').style.backgroundColor="#21ff1c";
	else if(temp1==41) document.getElementById('f41').style.backgroundColor="#21ff1c";
	else if(temp1==42) document.getElementById('f42').style.backgroundColor="#21ff1c";
	else if(temp1==43) document.getElementById('f43').style.backgroundColor="#21ff1c";
	else if(temp1==44) document.getElementById('f44').style.backgroundColor="#21ff1c";
	else if(temp1==45) document.getElementById('f45').style.backgroundColor="#21ff1c";
	else if(temp1==46) document.getElementById('f46').style.backgroundColor="#21ff1c";
	else if(temp1==47) document.getElementById('f47').style.backgroundColor="#21ff1c";
	else if(temp1==48) document.getElementById('f48').style.backgroundColor="#21ff1c";
	else if(temp1==49) document.getElementById('f49').style.backgroundColor="#21ff1c";
	else if(temp1==50) document.getElementById('f50').style.backgroundColor="#21ff1c";
	else if(temp1==51) document.getElementById('f51').style.backgroundColor="#21ff1c";
	else if(temp1==52) document.getElementById('f52').style.backgroundColor="#21ff1c";
	else if(temp1==53) document.getElementById('f53').style.backgroundColor="#21ff1c";
	else if(temp1==54) document.getElementById('f54').style.backgroundColor="#21ff1c";
	else if(temp1==55) document.getElementById('f55').style.backgroundColor="#21ff1c";
	else if(temp1==56) document.getElementById('f56').style.backgroundColor="#21ff1c";
	else if(temp1==57) document.getElementById('f57').style.backgroundColor="#21ff1c";
	else if(temp1==58) document.getElementById('f58').style.backgroundColor="#21ff1c";
	else if(temp1==59) document.getElementById('f59').style.backgroundColor="#21ff1c";
	else if(temp1==60) document.getElementById('f60').style.backgroundColor="#21ff1c";
	else if(temp1==61) document.getElementById('f61').style.backgroundColor="#21ff1c";
	else if(temp1==62) document.getElementById('f62').style.backgroundColor="#21ff1c";
	else if(temp1==63) document.getElementById('f63').style.backgroundColor="#21ff1c";
	else if(temp1==64) document.getElementById('f64').style.backgroundColor="#21ff1c";
	else if(temp1==65) document.getElementById('f65').style.backgroundColor="#21ff1c";
	else if(temp1==66) document.getElementById('f66').style.backgroundColor="#21ff1c";
	else if(temp1==67) document.getElementById('f67').style.backgroundColor="#21ff1c";
	else if(temp1==68) document.getElementById('f68').style.backgroundColor="#21ff1c";
	else if(temp1==69) document.getElementById('f69').style.backgroundColor="#21ff1c";
	else if(temp1==70) document.getElementById('f70').style.backgroundColor="#21ff1c";
	else if(temp1==71) document.getElementById('f71').style.backgroundColor="#21ff1c";
	else if(temp1==72) document.getElementById('f72').style.backgroundColor="#21ff1c";
	else if(temp1==73) document.getElementById('f73').style.backgroundColor="#21ff1c";
	else if(temp1==74) document.getElementById('f74').style.backgroundColor="#21ff1c";
	else if(temp1==75) document.getElementById('f75').style.backgroundColor="#21ff1c";
	else if(temp1==76) document.getElementById('f76').style.backgroundColor="#21ff1c";
	else if(temp1==77) document.getElementById('f77').style.backgroundColor="#21ff1c";
	else if(temp1==78) document.getElementById('f78').style.backgroundColor="#21ff1c";
	else if(temp1==79) document.getElementById('f79').style.backgroundColor="#21ff1c";
	else if(temp1==80) document.getElementById('f80').style.backgroundColor="#21ff1c";
	else if(temp1==81) document.getElementById('f81').style.backgroundColor="#21ff1c";
	else if(temp1==82) document.getElementById('f82').style.backgroundColor="#21ff1c";
	else if(temp1==83) document.getElementById('f83').style.backgroundColor="#21ff1c";
	else if(temp1==84) document.getElementById('f84').style.backgroundColor="#21ff1c";
	else if(temp1==85) document.getElementById('f85').style.backgroundColor="#21ff1c";
	else if(temp1==86) document.getElementById('f86').style.backgroundColor="#21ff1c";
	else if(temp1==87) document.getElementById('f87').style.backgroundColor="#21ff1c";
	else if(temp1==88) document.getElementById('f88').style.backgroundColor="#21ff1c";
	else if(temp1==89) document.getElementById('f89').style.backgroundColor="#21ff1c";
	else if(temp1==90) document.getElementById('f90').style.backgroundColor="#21ff1c";
	else if(temp1==91) document.getElementById('f91').style.backgroundColor="#21ff1c";
	else if(temp1==92) document.getElementById('f92').style.backgroundColor="#21ff1c";
	else if(temp1==93) document.getElementById('f93').style.backgroundColor="#21ff1c";
	else if(temp1==94) document.getElementById('f94').style.backgroundColor="#21ff1c";
	else if(temp1==95) document.getElementById('f95').style.backgroundColor="#21ff1c";
	else if(temp1==96) document.getElementById('f96').style.backgroundColor="#21ff1c";
	else if(temp1==97) document.getElementById('f97').style.backgroundColor="#21ff1c";
	else if(temp1==98) document.getElementById('f98').style.backgroundColor="#21ff1c";
	else if(temp1==99) document.getElementById('f99').style.backgroundColor="#21ff1c";
	else if(temp1==100) document.getElementById('f100').style.backgroundColor="#21ff1c";
		window.alert("You need"+" "+z+" "+"to win");
	}
	return a;	
}
function clearprep(b) {
if(b==1)document.getElementById("f1").style.backgroundColor="transparent";
else if(b==2)document.getElementById("f2").style.backgroundColor="transparent";
else if(b==3)document.getElementById("f3").style.backgroundColor="transparent";
else if(b==4)document.getElementById("f4").style.backgroundColor="transparent";
else if(b==5)document.getElementById("f5").style.backgroundColor="transparent";
else if(b==6)document.getElementById("f6").style.backgroundColor="transparent";
else if(b==7)document.getElementById("f7").style.backgroundColor="transparent";
else if(b==8)document.getElementById("f8").style.backgroundColor="transparent";
else if(b==9)document.getElementById("f9").style.backgroundColor="transparent";
else if(b==10)document.getElementById("f10").style.backgroundColor="transparent";
else if(b==11)document.getElementById("f11").style.backgroundColor="transparent";
else if(b==12)document.getElementById("f12").style.backgroundColor="transparent";
else if(b==13)document.getElementById("f13").style.backgroundColor="transparent";
else if(b==14)document.getElementById("f14").style.backgroundColor="transparent";
else if(b==15)document.getElementById("f15").style.backgroundColor="transparent";
else if(b==16)document.getElementById("f16").style.backgroundColor="transparent";
else if(b==17)document.getElementById("f17").style.backgroundColor="transparent";
else if(b==18)document.getElementById("f18").style.backgroundColor="transparent";
else if(b==19)document.getElementById("f19").style.backgroundColor="transparent";
else if(b==20)document.getElementById("f20").style.backgroundColor="transparent";
else if(b==21)document.getElementById("f21").style.backgroundColor="transparent";
else if(b==22)document.getElementById("f22").style.backgroundColor="transparent";
else if(b==23)document.getElementById("f23").style.backgroundColor="transparent";
else if(b==24)document.getElementById("f24").style.backgroundColor="transparent";
else if(b==25)document.getElementById("f25").style.backgroundColor="transparent";
else if(b==26)document.getElementById("f26").style.backgroundColor="transparent";
else if(b==27)document.getElementById("f27").style.backgroundColor="transparent";
else if(b==28)document.getElementById("f28").style.backgroundColor="transparent";
else if(b==29)document.getElementById("f29").style.backgroundColor="transparent";
else if(b==30)document.getElementById("f30").style.backgroundColor="transparent";
else if(b==31)document.getElementById("f31").style.backgroundColor="transparent";
else if(b==32)document.getElementById("f32").style.backgroundColor="transparent";
else if(b==33)document.getElementById("f33").style.backgroundColor="transparent";
else if(b==34)document.getElementById("f34").style.backgroundColor="transparent";
else if(b==35)document.getElementById("f35").style.backgroundColor="transparent";
else if(b==36)document.getElementById("f36").style.backgroundColor="transparent";
else if(b==37)document.getElementById("f37").style.backgroundColor="transparent";
else if(b==38)document.getElementById("f38").style.backgroundColor="transparent";
else if(b==39)document.getElementById("f39").style.backgroundColor="transparent";
else if(b==40)document.getElementById("f40").style.backgroundColor="transparent";
else if(b==41)document.getElementById("f41").style.backgroundColor="transparent";
else if(b==42)document.getElementById("f42").style.backgroundColor="transparent";
else if(b==43)document.getElementById("f43").style.backgroundColor="transparent";
else if(b==44)document.getElementById("f44").style.backgroundColor="transparent";
else if(b==45)document.getElementById("f45").style.backgroundColor="transparent";	
else if(b==46)document.getElementById("f46").style.backgroundColor="transparent";
else if(b==47)document.getElementById("f47").style.backgroundColor="transparent";
else if(b==48)document.getElementById("f48").style.backgroundColor="transparent";
else if(b==49)document.getElementById("f49").style.backgroundColor="transparent";
else if(b==50)document.getElementById("f50").style.backgroundColor="transparent";
else if(b==51)document.getElementById("f51").style.backgroundColor="transparent";
else if(b==52)document.getElementById("f52").style.backgroundColor="transparent";
else if(b==53)document.getElementById("f53").style.backgroundColor="transparent";
else if(b==54)document.getElementById("f54").style.backgroundColor="transparent";
else if(b==55)document.getElementById("f55").style.backgroundColor="transparent";
else if(b==56)document.getElementById("f56").style.backgroundColor="transparent";
else if(b==57)document.getElementById("f57").style.backgroundColor="transparent";
else if(b==58)document.getElementById("f58").style.backgroundColor="transparent";
else if(b==59)document.getElementById("f59").style.backgroundColor="transparent";
else if(b==60)document.getElementById("f60").style.backgroundColor="transparent";
else if(b==61)document.getElementById("f61").style.backgroundColor="transparent";
else if(b==62)document.getElementById("f62").style.backgroundColor="transparent";
else if(b==63)document.getElementById("f63").style.backgroundColor="transparent";
else if(b==64)document.getElementById("f64").style.backgroundColor="transparent";
else if(b==65)document.getElementById("f65").style.backgroundColor="transparent";
else if(b==66)document.getElementById("f66").style.backgroundColor="transparent";
else if(b==67)document.getElementById("f67").style.backgroundColor="transparent";
else if(b==68)document.getElementById("f68").style.backgroundColor="transparent";
else if(b==69)document.getElementById("f69").style.backgroundColor="transparent";
else if(b==70)document.getElementById("f70").style.backgroundColor="transparent";
else if(b==71)document.getElementById("f71").style.backgroundColor="transparent";
else if(b==72)document.getElementById("f72").style.backgroundColor="transparent";
else if(b==73)document.getElementById("f73").style.backgroundColor="transparent";
else if(b==74)document.getElementById("f74").style.backgroundColor="transparent";
else if(b==75)document.getElementById("f75").style.backgroundColor="transparent";
else if(b==76)document.getElementById("f76").style.backgroundColor="transparent";
else if(b==77)document.getElementById("f77").style.backgroundColor="transparent";
else if(b==78)document.getElementById("f78").style.backgroundColor="transparent";
else if(b==79)document.getElementById("f79").style.backgroundColor="transparent";
else if(b==80)document.getElementById("f80").style.backgroundColor="transparent";
else if(b==81)document.getElementById("f81").style.backgroundColor="transparent";
else if(b==82)document.getElementById("f82").style.backgroundColor="transparent";
else if(b==83)document.getElementById("f83").style.backgroundColor="transparent";
else if(b==84)document.getElementById("f84").style.backgroundColor="transparent";
else if(b==85)document.getElementById("f85").style.backgroundColor="transparent";
else if(b==86)document.getElementById("f86").style.backgroundColor="transparent";
else if(b==87)document.getElementById("f87").style.backgroundColor="transparent";
else if(b==88)document.getElementById("f88").style.backgroundColor="transparent";
else if(b==89)document.getElementById("f89").style.backgroundColor="transparent";
else if(b==90)document.getElementById("f90").style.backgroundColor="transparent";
else if(b==91)document.getElementById("f91").style.backgroundColor="transparent";
else if(b==92)document.getElementById("f92").style.backgroundColor="transparent";
else if(b==93)document.getElementById("f93").style.backgroundColor="transparent";
else if(b==94)document.getElementById("f94").style.backgroundColor="transparent";
else if(b==95)document.getElementById("f95").style.backgroundColor="transparent";
else if(b==96)document.getElementById("f96").style.backgroundColor="transparent";
else if(b==97)document.getElementById("f97").style.backgroundColor="transparent";
else if(b==98)document.getElementById("f98").style.backgroundColor="transparent";
else if(b==99)document.getElementById("f99").style.backgroundColor="transparent";
else if(b==100)document.getElementById("f100").style.backgroundColor="transparent";
}


function restart() {
window.location.href="index.html?submit=Start";
}